# Generated by Django 4.1 on 2023-09-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=100)),
                ('data_description', models.TextField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.industrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_data', models.JSONField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.industrymodel')),
            ],
        ),
    ]
