# Generated by Django 4.1 on 2023-09-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrymodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='requireddatamodel',
            name='data_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
