# Generated by Django 4.1 on 2023-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_industrymodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddatamodel',
            name='data_name',
            field=models.CharField(max_length=100),
        ),
    ]
