# Generated by Django 4.1 on 2023-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_forecastmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requireddatamodel',
            name='industry',
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='industry',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Automotive', 'Automotive'), ('Hospitality', 'Hospitality')], max_length=50),
        ),
        migrations.DeleteModel(
            name='IndustryModel',
        ),
        migrations.DeleteModel(
            name='RequiredDataModel',
        ),
    ]
