"""
Django settings for thesis_app project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gi)+_yn#@11%ge*sloess_mm2vfo4^g*qe1q(f5@n+opc+2l)t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Default Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party Apps
    'rest_framework',

    # Own Apps
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'thesis_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'thesis_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth

LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = 'index'

LOGOUT_REDIRECT_URL = 'login'


# Industries and Required Data

INDUSTRIES = [
    {
        "Industry": "Retail",
        "Description": "The retail industry involves the sale of goods directly to consumers. It includes various types of businesses such as department stores, supermarkets, and online retailers.",
        "Attributes": [
            {
                "Name": "Revenue",
                "Type": "integer",
                "Description": "The total month revenue."
            },
            {
                "Name": "Average Transaction Value",
                "Type": "numeric",
                "Description": "It is calculated by dividing monthly sales by the number of transactions."
            },
            {
                "Name": "Number of Transactions",
                "Type": "integer",
                "Description": "The total count of transactions."
            },
            {
                "Name": "Date",
                "Type": "date",
                "Description": "The date associated with the data."
            }
        ],
        "SampleJSON": '''[
    {
        "Revenue": 557716,
        "Average Transaction Value": 111.54,
        "Number of Transactions": 5000,
        "Date": "2020-01"
    },
    {
        "Revenue": 569188,
        "Average Transaction Value": 109.46,
        "Number of Transactions": 5200,
        "Date": "2020-02"
    }
]''',
        "SampleCSV": '''Revenue,Average Transaction Value,Number of Transactions,Date
557716,50.25,5000,2020-01
569188,51.2,5200,2020-02'''
    },
    {
        "Industry": "Technology",
        "Description": "The technology industry focuses on the development, manufacturing, and distribution of technological products and services. This includes software, hardware, electronics, and telecommunications.",
        "Attributes": [
            {
                "Name": "Revenue",
                "Type": "integer",
                "Description": "The total month revenue."
            },
            {
                "Name": "Number of New Product Launches",
                "Type": "integer",
                "Description": "The total count of new product launches."
            },
            {
                "Name": "Sold Units",
                "Type": "integer",
                "Description": "The total sold of units."
            },
            {
                "Name": "Date",
                "Type": "date",
                "Description": "The date associated with the data."
            }
        ],
        "SampleJSON": '''[
    {
      "Revenue": 50000,
      "Number of New Product Launches": 3,
      "Sold Units": 10000,
      "Date": "2020-01"
    },
    {
      "Revenue": 55000,
      "Number of New Product Launches": 4,
      "Sold Units": 11000,
      "Date": "2020-02"
    }
]''',
        "SampleCSV": '''Revenue,Number of New Product Launches,Sold Units,Date
50000,3,10000,2020-01
55000,4,11000,2020-02'''
    },
    {
        "Industry": "Healthcare",
        "Description": "The healthcare industry encompasses medical services, facilities, and products that promote health, diagnose and treat illnesses, and improve overall well-being.",
        "Attributes": [
            {
                "Name": "Revenue",
                "Type": "integer",
                "Description": "The total month revenue."
            },
            {
                "Name": "Number of Patient Visits",
                "Type": "integer",
                "Description": "The total count of patient visits."
            },
            {
                "Name": "Average Billing Amount",
                "Type": "numeric",
                "Description": "The average billing amount for patient visits."
            },
            {
                "Name": "Date",
                "Type": "date",
                "Description": "The date associated with the data."
            }
        ],
        "SampleJSON": '''[
    {
      "Revenue": 120000,
      "Number of Patient Visits": 1500,
      "Average Billing Amount": 80.0,
      "Date": "2020-01"
    },
    {
      "Revenue": 130000,
      "Number of Patient Visits": 1600,
      "Average Billing Amount": 81.25,
      "Date": "2020-02"
    }
]''',
        "SampleCSV": '''Revenue,Number of Patient Visits,Average Billing Amount,Date
120000,1500,80,2020-01
130000,1600,81.25,2020-02'''
    },
    {
        "Industry": "Automotive",
        "Description": "The automotive industry involves the design, manufacturing, marketing, and selling of vehicles such as cars, trucks, and motorcycles. It also includes related services and components.",
        "Attributes": [
            {
                "Name": "Revenue",
                "Type": "integer",
                "Description": "The total month revenue."
            },
            {
                "Name": "Number of Vehicle Sales",
                "Type": "integer",
                "Description": "The total count of vehicle sales."
            },
            {
                "Name": "Average Vehicle Price",
                "Type": "numeric",
                "Description": "The average price of vehicles sold."
            },
            {
                "Name": "Date",
                "Type": "date",
                "Description": "The date associated with the data."
            }
        ],
        "SampleJSON": '''[
    {
      "Revenue": 2500000,
      "Number of Vehicle Sales": 1000,
      "Average Vehicle Price": 25000.0,
      "Date": "2020-01"
    },
    {
      "Revenue": 2600000,
      "Number of Vehicle Sales": 1050,
      "Average Vehicle Price": 24761.9,
      "Date": "2020-02"
    }
]''',
        "SampleCSV": '''Revenue,Number of Vehicle Sales,Average Vehicle Price,Date
2500000,1000,25000,2020-01
2600000,1050,24761.9,2020-02'''
    },
    {
        "Industry": "Hospitality",
        "Description": "The hospitality industry covers services related to accommodation, dining, entertainment, and tourism. It includes hotels, restaurants, travel agencies, and event planning.",
        "Attributes": [
            {
                "Name": "Revenue",
                "Type": "integer",
                "Description": "The total month revenue."
            },
            {
                "Name": "Number of Bookings",
                "Type": "integer",
                "Description": "The total count of bookings."
            },
            {
                "Name": "Average Room Rate",
                "Type": "numeric",
                "Description": "The average rate charged for rooms."
            },
            {
                "Name": "Date",
                "Type": "date",
                "Description": "The date associated with the data."
            }
        ],
        "SampleJSON": '''[
    {
      "Revenue": 750000,
      "Number of Bookings": 300,
      "Average Room Rate": 250.0,
      "Date": "2020-01"
    },
    {
      "Revenue": 780000,
      "Number of Bookings": 312,
      "Average Room Rate": 250.0,
      "Date": "2020-02"
    }
]''',
        "SampleCSV": '''Revenue,Number of Bookings,Average Room Rate,Date
750000,300,250,2020-01
780000,312,250,2020-02'''
    }
]
